### ISSUE TITLE
Handle Tinypass timeouts

### ISSUE THREAD

**Issue by genexp** [oddnetworks/seneca-odd-entitlement#1]
Tinypass is down.  Ahh!  Let's handle timeouts better.

From:  https://www.npmjs.com/package/request

````
timeout - Integer containing the number of milliseconds to wait for a server to send response headers (and start the response body) before aborting the request. Note that if the underlying TCP connection cannot be established, the OS-wide TCP connection timeout will overrule the timeout option (the default in Linux can be anywhere from 20-120 seconds).
````

We need to make read timeout for Tinypass much lower (5s?)  

We should also return a response with a caching header.

**Comment by genexp** [comment]
@kixxauth @blainsmith Copying you here.

**Comment by kixxauth** [comment]
Agreed, the timeout for Tinypass can probably be lower. I don't know that code well, so can't say for sure, but it seems like that would be a good idea.

I think we're limited about how much caching we can have in place between the device and our servers on the routes involved in device linking. Let's do as much as reasonable, but I think we need to contemplate some architectural changes so we can respond to this sort of perfect storm.

That said, there may not be a whole lot we can do, besides understand when this might happen (a bunch of new, un-authed users, all trying to auth at the same time). Then, know when we need to add application servers, probably manually, until the spike subsides.

**Comment by tquackenbush** [comment]
Added a 5s timeout to tinyPass entitlement requests.
This won't help un-authed users, but will help if someone is already linked and tinyPass is taking too long to respond for some reason.
(entitlements only get fetched if someone is authed)

https://github.com/oddnetworks/seneca-odd-entitlement/commit/0a2b748014936a37cbc9e97d829e4f544b706f00

**Comment by genexp** [comment]
Yeah. We should defend against unexpected traffic though, like mistakes in
client implementations. Reminds me of a certain video game that bombed due
to a 10ms retry with no offset :(

**Comment by kixxauth** [comment]
In order to fully implement a defense we'd need to throttle based on IP address, right @genexp ? Is that what you're thinking (long term)?

**Comment by genexp** [comment]
I guess I was thinking we could let individual actions specify the max age,
then use a default if it's not specified.
